### ISSUE TITLE
 Error: Cannot find module

### ISSUE THREAD

**Issue by Igor-Maf** [PavelVanecek/gulp-crx#11]
http://joxi.ru/eAOYo8wH4LZ40m

Also the variable of manifest was added at the top of gulpfile. 
`const fs = require("fs");
let manifest = require('./dist/manifest.json');`
The next task, after 'crx-pack', 'package' uses this variable also but works fine

**Comment by PavelVanecek** [comment]
Hi Igor, can you please provide some project or snippet to reproduce this? I will try to find the cause but it works fine on my machine.

**Comment by Igor-Maf** [comment]
Hi, Pavel. 
Yes, you can see the [test project here](https://github.com/Igor-Maf/env-crx).
Please, let me know when you`ll fix the problem. Thx

**Comment by PavelVanecek** [comment]
Your gulpfile was misconfigured - the package expects folder, you gave it file list.

**Comment by Igor-Maf** [comment]
Thx, Pavel. Sorry to trouble you
