### ISSUE TITLE
Register a new npm module

### ISSUE THREAD

**Issue by jhen0409** [PavelVanecek/gulp-crx#2]
Hey, this fork is great work. :)
The [upstream](https://github.com/evanxd/gulp-crx/pull/2) is no responses long time, I think you should to register a new npm module. Although we can manage version by commits, but it not perfect in `package.json`. :(

**Comment by PavelVanecek** [comment]
I was kind of hoping that @evanxd notices the PR https://github.com/evanxd/gulp-crx/pull/2 and republishes. Well, nevermind.

**Comment by jhen0409** [comment]
Thanks! :+1: 
Can you check it really published? It is not found.

**Comment by PavelVanecek** [comment]
Weird. I did publish another version just to see if that helps, but npmjs.com shows two different informations (both of them wrong):

![screen shot 2015-11-27 at 10 19 19](https://cloud.githubusercontent.com/assets/1100170/11437738/658446e0-94f0-11e5-90e6-7509c5e5cd11.png) ![screen shot 2015-11-27 at 10 19 11](https://cloud.githubusercontent.com/assets/1100170/11437740/6a31db80-94f0-11e5-8bdc-a06b3de9d1d3.png)

Do you have any idea how to fix it? Looks like caching issues to me.

**Comment by SpeCT** [comment]
First of all thank you for this fork :+1: 

Second. It seems like everything is fine with your new module. I've just installed it from npm:

```
$ npm install gulp-crx-pack --save-dev
npm WARN engine crx@3.0.3: wanted: {"node":">=0.10","iojs":">=1.0.0 <2.0.0","npm":">=2.13.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
gulp-crx-pack@1.0.1 node_modules/gulp-crx-pack
├── merge@1.2.0
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
└── crx@3.0.3 (wrench@1.5.8, es6-promise@2.3.0, commander@2.9.0, temp@0.8.3, node-rsa@0.2.26, archiver@0.8.1)
$ head node_modules/gulp-crx-pack/package.json
{
  "name": "gulp-crx-pack",
  "version": "1.0.1",
  "description": "Pack Chrome Extension in the pipeline.",
  "homepage": "https://github.com/PavelVanecek/gulp-crx",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/PavelVanecek/gulp-crx.git"
```

You should probably clean your local npm cache.

**Comment by PavelVanecek** [comment]
I believe it is okay now
