### ISSUE TITLE
CRX3 support

### ISSUE THREAD

**Issue by xvilo** [PavelVanecek/gulp-crx#26]
Hi,

CRX files produced by this plugin are not valid as of a few days ago. This is because the CRX3 format is now required. Is there support for this pithing the package? Will there be support?

**Comment by xvilo** [comment]
https://github.com/PavelVanecek/gulp-crx/pull/27

**Comment by ayoseturru** [comment]
It would be great to support the nex CRX format and publish it into npm library too.
