### ISSUE TITLE
Cannot find module : 'manifest'

### ISSUE THREAD

**Issue by nitinsurana** [PavelVanecek/gulp-crx#4]
```
var manifest = require('manifest');
```

Running gives `Cannot find module: manifest`, probably related to the above line. Which package to install ?

**Comment by PavelVanecek** [comment]
This is actually a mistake in the README example. The require should ask for the `manifest.json` file in the extension root.

**Comment by nitinsurana** [comment]
Yup, just figured `manifest` is not some node module, we can actually read `manifest.json` using `require` command.
