### ISSUE TITLE
[Error: Error: It is not public key]

### ISSUE THREAD

**Issue by nitinsurana** [PavelVanecek/gulp-crx#5]
Commenting the privateKey line and running the task gives the following error :

```
[Error: Error: It is not public key]
```

According to the docs, privateKey is optional.

**Comment by PavelVanecek** [comment]
Which document says that privateKey is optional? As far as I know it is mandatory on purpose, because you don't want to generate new key pair on every build.

**Comment by nitinsurana** [comment]
`Pack extension` in `chrome://extensions` let's pack without key. There it says `optional`. I used that to create the key and then used it in the extension :)

**Comment by PavelVanecek** [comment]
This package is independent on Chrome and the intent is to automate the process so you do not have to click around in GUI every time you want to deploy. It also works on systems where Chrome is not installed at all.
The key can be generated by one-time Chrome packaging like you did, or `ssh-keygen`, or other means, and I think it can stay that way.
